// <auto-generated />
using System;
using Haulmer.Payments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Haulmer.Payments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260312174121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Haulmer.Payments.Domain.Catalogs.Acquirer", b =>
                {
                    b.Property<long>("AcquirerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AcquirerId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AcquirerId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Acquirers", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Catalogs.PaymentChannel", b =>
                {
                    b.Property<long>("PaymentChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentChannelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentChannelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("PaymentChannels", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Catalogs.PaymentMethod", b =>
                {
                    b.Property<long>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentMethodId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("PaymentMethods", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.MerchantSetup.MerchantAcquirerConfiguration", b =>
                {
                    b.Property<long>("MerchantAcquirerConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MerchantAcquirerConfigurationId"));

                    b.Property<long>("AcquirerId")
                        .HasColumnType("bigint");

                    b.Property<string>("AcquirerMerchantCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<string>("MerchantTerminalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PaymentChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MerchantAcquirerConfigurationId");

                    b.HasIndex("AcquirerId");

                    b.HasIndex("PaymentChannelId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("MerchantId", "PaymentMethodId", "PaymentChannelId", "Currency", "Status");

                    b.ToTable("MerchantAcquirerConfigurations", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.MerchantSetup.MerchantPaymentMethod", b =>
                {
                    b.Property<long>("MerchantPaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MerchantPaymentMethodId"));

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnabledFromLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnabledFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnabledToLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnabledToUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MerchantPaymentMethodId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("MerchantId", "PaymentMethodId");

                    b.ToTable("MerchantPaymentMethods", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.MerchantSetup.MerchantPricing", b =>
                {
                    b.Property<long>("MerchantPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MerchantPricingId"));

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("FixedFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OtherChargePercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("PaymentChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidFromLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidToLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VariableFeePercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VatPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("MerchantPricingId");

                    b.HasIndex("PaymentChannelId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("MerchantId", "PaymentMethodId", "PaymentChannelId", "Currency", "Status");

                    b.ToTable("MerchantPricings", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Merchants.Merchant", b =>
                {
                    b.Property<long>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MerchantId"));

                    b.Property<string>("BusinessLegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyRut")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadOfficeAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MerchantId");

                    b.HasIndex("CompanyRut")
                        .IsUnique();

                    b.HasIndex("MerchantCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Merchants", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Merchants.MerchantBranch", b =>
                {
                    b.Property<long>("MerchantBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MerchantBranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MerchantBranchId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Status");

                    b.HasIndex("MerchantId", "BranchCode")
                        .IsUnique();

                    b.ToTable("MerchantBranches", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentIdempotency", b =>
                {
                    b.Property<long>("PaymentIdempotencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentIdempotencyId"));

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentIdempotencyId");

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("Status");

                    b.HasIndex("MerchantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("PaymentIdempotencies", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentRequest", b =>
                {
                    b.Property<long>("PaymentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentRequestId"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("PaymentRequests", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentTraceLog", b =>
                {
                    b.Property<long>("PaymentTraceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentTraceLogId"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventSource")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentTransactionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("PaymentTraceLogId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("PaymentTraceLogs", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentTransaction", b =>
                {
                    b.Property<long>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentTransactionId"));

                    b.Property<long>("AcquirerId")
                        .HasColumnType("bigint");

                    b.Property<string>("AcquirerReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CardLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IssuingBankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("MerchantAcquirerConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<long>("MerchantBranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<long>("MerchantPaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherChargesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayerFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayerRut")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long>("PaymentChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("AcquirerId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("MerchantAcquirerConfigurationId");

                    b.HasIndex("MerchantBranchId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("MerchantPaymentMethodId");

                    b.HasIndex("PaymentChannelId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("TransactionNumber")
                        .IsUnique();

                    b.HasIndex("MerchantId", "CurrentStatus");

                    b.ToTable("PaymentTransactions", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentTransactionStatusHistory", b =>
                {
                    b.Property<long>("PaymentTransactionStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentTransactionStatusHistoryId"));

                    b.Property<string>("AcquirerResponseCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AcquirerResponseMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentTransactionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusReasonDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PaymentTransactionStatusHistoryId");

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("PaymentTransactionId", "CreatedAtUtc");

                    b.ToTable("PaymentTransactionStatusHistories", "payments");
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.MerchantSetup.MerchantAcquirerConfiguration", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Catalogs.Acquirer", null)
                        .WithMany()
                        .HasForeignKey("AcquirerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentChannel", null)
                        .WithMany()
                        .HasForeignKey("PaymentChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.MerchantSetup.MerchantPaymentMethod", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.MerchantSetup.MerchantPricing", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentChannel", null)
                        .WithMany()
                        .HasForeignKey("PaymentChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Merchants.MerchantBranch", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentIdempotency", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Payments.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentRequest", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Payments.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentTraceLog", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Haulmer.Payments.Domain.Payments.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentTransaction", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Catalogs.Acquirer", null)
                        .WithMany()
                        .HasForeignKey("AcquirerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.MerchantSetup.MerchantAcquirerConfiguration", null)
                        .WithMany()
                        .HasForeignKey("MerchantAcquirerConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Merchants.MerchantBranch", null)
                        .WithMany()
                        .HasForeignKey("MerchantBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.MerchantSetup.MerchantPaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("MerchantPaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentChannel", null)
                        .WithMany()
                        .HasForeignKey("PaymentChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haulmer.Payments.Domain.Catalogs.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulmer.Payments.Domain.Payments.PaymentTransactionStatusHistory", b =>
                {
                    b.HasOne("Haulmer.Payments.Domain.Payments.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
